apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-name

secretGenerator:
- name: app-name-sso-provider-secret
  envs:
  - .env.secret
- name: app-name-observability
  envs:
  - .env.secret

generatorOptions:
  disableNameSuffixHash: true
  
resources:
  - git1/app-depolyment.yaml
  - git1/api-routes.yaml
  - git2/app-depolyment.yaml
  - git2/api-routes.yaml
  - mapping.yaml
  - gateway.yaml
 

